spring.datasource.url=jdbc:postgresql://localhost:5432/userrolesystem
spring.datasource.username=postgres
spring.datasource.password=Sibhadt
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

app.jwt.secret=mySecretKey123456789012345678901234567890123456789012345678901234
app.jwt.expiration=86400000
app.jwt.refresh-expiration=604800000